# Generated by Django 6.0 on 2025-12-28 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Marque')),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="Nom complet de l'employé")),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Type d'équipement")),
            ],
            options={
                'verbose_name': "Type d'équipement",
                'verbose_name_plural': "Types d'équipement",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du site')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Numéro de série')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name="Date d'achat")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.employee', verbose_name='Attribué à')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.brand', verbose_name='Marque')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.equipmenttype', verbose_name="Type d'équipement")),
                ('site', models.ManyToManyField(blank=True, to='home.site', verbose_name='Sites')),
            ],
            options={
                'verbose_name': "Élément d'inventaire",
                'verbose_name_plural': "Éléments d'inventaire",
                'ordering': ['brand', 'model'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='sites',
            field=models.ManyToManyField(blank=True, to='home.site', verbose_name="Sites d'affectation"),
        ),
    ]
