# Generated by Django 5.2.7 on 2025-10-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('laptop', 'PC Portable'), ('desktop', 'PC Fixe'), ('monitor', 'Écran'), ('printer', 'Imprimante'), ('other', 'Autre')], max_length=20, verbose_name="Type d'équipement")),
                ('brand', models.CharField(max_length=100, verbose_name='Marque')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Numéro de série')),
                ('assigned_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Attribué à')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name="Date d'achat")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': "Élément d'inventaire",
                'verbose_name_plural': "Éléments d'inventaire",
                'ordering': ['brand', 'model'],
            },
        ),
    ]
