# Generated by Django 5.2.7 on 2025-10-27 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Marque')),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Type d'équipement")),
            ],
            options={
                'verbose_name': "Type d'équipement",
                'verbose_name_plural': "Types d'équipement",
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.brand', verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.equipmenttype', verbose_name="Type d'équipement"),
        ),
    ]
